### ISSUE TITLE
Different marker distributions between samples

### ISSUE THREAD

**Issue by marcovarrone** [CamaraLab/STvEA#12]
Thank you for the pipeline, it's helping me a lot in analyzing CODEX data.

I am following the code on codex_tutorial.md for preprocessing the BALBc data from Goltsev et al. using the fcs provided by the authors of the study.

However, after filtering and cleaning each dataset separately, if I compare the distributions of a marker between datasets, sometimes I get very different results. 

For example, comparing BALBc-1 and BALBc-2 the distribution of CD45 is quite similar:
![Screenshot 2021-04-14 at 09 10 23](https://user-images.githubusercontent.com/9199935/114668763-64680980-9d01-11eb-9e66-cb1d5785724d.png)

However, for Ly6C they are extremely different:
![Screenshot 2021-04-14 at 09 10 14](https://user-images.githubusercontent.com/9199935/114668820-75b11600-9d01-11eb-9630-92f273a45fbe.png)

This also leads to a clear separation in the UMAP between the datasets. This separation is not present in the original data, so it's not caused by a batch effect.

I tried to use as values for the parameters of FilterCODEX either the ones specified in the tutorial, or leave them blank, but the conclusions are always the same.

Did you already encounter this problem? How can I solve it?

**Comment by govekk** [comment]
This is a good issue to point out. This occurs when there is no clear signal in the raw protein expression, or the background expression levels are too close to the signal. The Gaussian mixture fits two distributions to the same curve, and it becomes a toss up which one is chosen as “signal” or “background” since they are too close. This occurs most with Ly6C, Ter119, and CD3 in the CODEX dataset of Goltsev et al. 

We did not worry about this much in our study since those proteins did not mark clear cell types even in the raw expression, and we found that removing or keeping them did not impact future analyses much. 

If you wish to still use those proteins, we have found that for datasets where the Gaussian mixture model does not provide a good fit, an arcsinh transformation is a useful alternative, though it doesn’t take into account the separation between signal and background as well.
