### ISSUE TITLE
CleanCODEX()  error

### ISSUE THREAD

**Issue by afcmalone** [CamaraLab/STvEA#9]
Hi,
I love this tool and am trying to apply it to my data.
I get this error when running the CODEX only tutorial on my data:

stvea_object <- CleanCODEX(stvea_object)
Error in quantile.default(x, seq(from = 0, to = 1, length = n)) : 
  missing values and NaN's not allowed if 'na.rm' is FALSE

Is this error because my codex_protein matrix is much smaller than my codex_spatial matrix as the markers i used only bind to a subset of cells in my tissue sample.

Is it possible to run STvEA on such data?

Thanks
Andrew

**Comment by govekk** [comment]
Hi Andrew,

STvEA does expect that you have the same number of cells in your codex_spatial matrix as your codex_protein matrix - otherwise the plotting functions won't work. You would either have to subset the codex_protein matrix to be the same size as the codex_spatial, or add rows of 0s (or your minimum expression value) for each missing cell in the codex_protein matrix.

I don't know if this is exactly creating the error you are seeing - you might want to check that the stvea_object@codex_protein matrix is the expected size and contains no NAs before calling CleanCODEX(). It is possible that the FilterCODEX() function is creating NAs if your codex_blank matrix is also larger than your codex_protein matrix.

Hope this helps! Let me know if you keep getting the same error.
-Kiya

**Comment by afcmalone** [comment]
Hi Kiya,
Thanks for your answer.
Using this code:
codex_subset <- codex_spatial$x < 3000 & codex_spatial$y < 3000
codex_protein <- codex_protein[codex_subset,]
codex_blanks <- codex_blanks[codex_subset,]
codex_size <- codex_size[codex_subset]
codex_spatial_nm <- codex_spatial_nm[codex_subset,]

The 'codex_size' object seems to be loaded into R at the 'library(STvEA)' stage.
Then running 'codex_size <- codex_size[codex_subset]' gives a row number that is not consistent with my data.

Is this intentional?

Thanks
Andrew

**Comment by govekk** [comment]
Hi Andrew,

See my comment on another recent issue (https://github.com/CamaraLab/STvEA/issues/11#issuecomment-817834022) for more information on where we got the codex_protein, codex_blanks, codex_size, and codex_spatial matrices. You will want to use these matrices from your own dataset, not the ones preloaded for the tutorial. 

If your dataset does not contain size or blank columns, you can create fake matrices with the same number of cells and adjust the min/max parameters in FilterCODEX so that no cells get removed. In the future I will likely implement a data intake method to retrieve this information directly from the FCS or CSV, or allow for datasets without these columns.

Let me know if you have any other questions,
-Kiya

**Comment by afcmalone** [comment]
Hi Kiya,
I have managed to get your code to take seurat v3 data which is great. 
To integrate CITEseq object with the CODEX object do you need to have all CODEX antibodies and all the CITEseq antibodies to be the same or does there only need to be some overlap? And then, what is the minimal number of common antibodies needed for integration to work and for meaningful clusters to be generated?
Finally, presume the CITEseq antibody names need to be exactly the same as the CODEX antibody names.

Thanks,
Andrew

**Comment by govekk** [comment]
Hi Andrew,
All antibodies used in the CITEseq-CODEX integration need to be the same. In particular, the protein expression matrices should have the same ordering of columns. We have successfully integrated both CODEX and CyTOF data using only a subset of the panel, but you must pass only that subset into STvEA. 
See our supplementary figure 11 (https://advances.sciencemag.org/content/suppl/2021/03/01/7.10.eabc5464.DC1) for an analysis on the affect of the number of common antibodies in the integration. 
-Kiya
